### ISSUE TITLE
SimpleReservoirSampling 

### ISSUE THREAD

**Issue by WenjuanW** [proteus-h2020/SOLMA#9]
Hi, I have got some questions about the code SimpleReservoirSampling

1. Is the SimpleReservoirSampling code distributed? ( It can run on many partitioned streams?)

2. Line 89: `var (streamCounter, reservoirCounter, reservoir) = curr`
Is reservoirCounter the counter of how many distributed DataStream? What is reservoirCounter for?

From Line 91 to 94, according to the reservoir sampling algorithm, the **if condition** should be when the _counter(of data stream) < k (reservoir size)_ , we keep the data point in the reservoir. Therefore, it should be _streamCounter < k_ in this code.

Thanks!

**Comment by waqasjamyl** [comment]
I think the answers to your first two questions is ,es, and indeed that implies that there is a bug in the implementation.

**Comment by VenturaDelMonte** [comment]
Hi @WenjuanW, good catch! Actually, the usage of `reservoirCounter` is redundant and could potentially lead to a OBOE. Thank you for your reviewing the initial implementation. At this point, I would ask you to review also the fix, please. If you spot any other mistake, please feel free to report it in the PR form.

**Comment by WenjuanW** [comment]
You are welcome :100:
